### ISSUE TITLE
Refactoring feedback

### ISSUE THREAD

**Issue by letsar** [letsar/flutter_slidable#186]
Hey flutter_slidable users 👋  !

Since one month I've been working on a full rewrite of this package in order to decouple a lot of things and also to make it more flexible.

You will find below a list of some features I've added along this refactoring:
- Have different threshold for start and end action panes.
- Have different **motions** (the widget which controls how the action pane animates when the user drags the Slidable).
- Choose if the user can dismiss the start or the end pane, or both, and have different threshold for both of them.
- Create your own motions easier.

Today I think we have something usable, but I would need some feedback from you before finishing the documentation and  publishing the package.

If you want to help me and make this package better, you can test this refactoring on feature/revival by setting this in your pubspec.yaml:
```yaml
dependencies:
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable
      ref: feature/revival
```

I'm open to any suggestions if it doesn't involve another full rewrite 😅 ! So don't hesitate.
If you find bugs, please fill an issue with [revival] in the title.

Don't use this in a production code, because renamings can still happen.
