### ISSUE TITLE
Compilation failed on 3.27.0 `The method 'hashValues' isn't defined for the class 'SlidableRatioNotification'`

### ISSUE THREAD

**Issue by mdddj** [letsar/flutter_slidable#511]
flutter version: 3.27.0
```dart
Could not build the precompiled application for the device.
Error (Xcode): ../.pub-cache/hosted/pub.dev/flutter_slidable-3.1.1/lib/src/notifications_old.dart:88:23: Error: The method 'hashValues' isn't defined for the class 'SlidableRatioNotification'.

```

**Comment by jayrao5566** [comment]
flutter_slidable:
        git:
            url: https://github.com/letsar/flutter_slidable.git

**Comment by jayrao5566** [comment]
`flutter_slidable:
        git:
            url: https://github.com/letsar/flutter_slidable.git`

**Comment by mdddj** [comment]
Temporary solution, the author seems to have not updated to pub.dev yet
```yaml
  flutter_slidable:
    git:
      url: "https://github.com/letsar/flutter_slidable"
```
